# Generated by Django 4.1.1 on 2022-09-21 21:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('cvm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='duration',
            field=models.CharField(max_length=200),
        ),
    ]
